### 배열 생성하기

In [1]:
!pip install numpy

In [3]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [5]:
a1.dtype

dtype('int32')

In [6]:
a2.dtype

dtype('float64')

In [7]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [22]:
np.array([[1,2,3], [4,5,6], [7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 배열 생성

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [20]:
np.linspace(1, 10, 10)
# 1부터 10까지의 수를 10개의 간격으로 나눈 값을 반환 얘는 10까지 반환

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 특별한 형태의 배열 생성

In [1]:
import numpy as np

In [9]:
print(np.zeros(10))
print(np.zeros((3,4)))
print(np.ones(10))
print(np.ones((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환

In [21]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [22]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [24]:
str_a1.dtype

dtype('<U5')

In [25]:
num_a1.dtype

dtype('float64')

In [26]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [27]:
str_a2.dtype

dtype('<U1')

In [28]:
num_a2.dtype

dtype('int32')

In [30]:
num_f1 = np.array([10, 21, 0.0549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [31]:
num_f1.dtype

dtype('float64')

In [32]:
num_i1.dtype

dtype('int32')

#### 난수 배열의 생성

In [34]:
np.random.rand(2,3)

array([[0.70618093, 0.56214515, 0.60228526],
       [0.64982178, 0.15603257, 0.38833061]])

In [35]:
np.random.rand()

0.6005553534797848

In [36]:
np.random.rand(2,3,4)

array([[[0.49902431, 0.41299618, 0.69571975, 0.44236076],
        [0.56518161, 0.99957949, 0.57350596, 0.75647715],
        [0.23460761, 0.89664958, 0.75875272, 0.9741481 ]],

       [[0.67043341, 0.6144799 , 0.78105582, 0.67366552],
        [0.02692135, 0.3465578 , 0.40991047, 0.10420875],
        [0.27430556, 0.7861977 , 0.07524016, 0.22155074]]])

In [74]:
np.random.randint(10, size=(3,4))

array([[2, 7, 9, 4],
       [2, 2, 5, 4],
       [2, 8, 1, 4]])

In [80]:
np.random.randint(1, 46, 6)


array([15, 15, 31, 35, 40, 22])

### 배열의 연산

#### 기본연산

In [89]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print((arr2*2))
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 / (arr2 **2))
print(arr1 > 20)

[11 22 33 44]
[ 9 18 27 36]
[2 4 6 8]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10.          5.          3.33333333  2.5       ]
[False False  True  True]


#### 통계를 위한 연산

In [107]:
arr3 = np.arange(5)
print(arr3)
print([sum(arr3), arr3.mean()])   #배열 합과 평균
print([arr3.std(), arr3.var()])   # 배열 표준편차와 분산
print([arr3.min(), arr3.max()])  # 배열 최솟값과 최댓값

[0 1 2 3 4]
[10, 2.0]
[1.4142135623730951, 2.0]
[0, 4]


In [112]:
arr4 = np.arange(1, 5)
print(arr4)
print(arr4.cumsum(), arr4.dtype)   # 배열의 누적 합
print(arr4.cumprod(), arr4.dtype)  # 배열의 누적 곱

[1 2 3 4]
[ 1  3  6 10] int32
[ 1  2  6 24] int32


#### 행렬연산

In [119]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
print(A, "\n")
B = np.array([3, 2, 0, 1]).reshape(2,2)
print(B)

[[0 1]
 [2 3]] 

[[3 2]
 [0 1]]


In [125]:
print(A.dot(B), '\n')    # 행렬 곱

print(np.dot(A,B))

[[0 1]
 [6 7]] 

[[0 1]
 [6 7]]


In [128]:
print(np.transpose(A), '\n')  # 전치 행렬
print(A.transpose())

[[0 2]
 [1 3]] 

[[0 2]
 [1 3]]


In [131]:
print(np.linalg.inv(A), '\n')  # 역행렬
print(np.linalg.det(A))  # 행렬식

[[-1.5  0.5]
 [ 1.   0. ]] 

-2.0


### 배열의 인덱싱과 슬라이싱

In [137]:
a1 = np.array([0, 10, 20, 30, 40, 50])
print(a1)
print(a1[4])
a1[5] = 70
print(a1)
print(a1[[1,3,4]])

[ 0 10 20 30 40 50]
40
[ 0 10 20 30 40 70]
[10 30 40]


In [160]:
a2 = np.arange(10, 100, 10).reshape(3,3)
print(a2, '\n')

print(a2[0,2], '\n')  # a2의 0행 2열 값 반환

a2[2,2] = 95

print(a2, '\n')
print(a2[1], '\n')  # a2의 1행 값 반환

a2[1] = np.array([45, 55, 65])
print(a2, '\n')

print(a2[[0,2], [0,1]])  #각 행렬 교차값 반환

[[10 20 30]
 [40 50 60]
 [70 80 90]] 

30 

[[10 20 30]
 [40 50 60]
 [70 80 95]] 

[40 50 60] 

[[10 20 30]
 [45 55 65]
 [70 80 95]] 

[10 80]


In [169]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a>3])
print(a[(a%2)==0])

[4 5 6]
[2 4 6]


#### 배열의 슬라이싱

In [176]:
b1 = np.array([0, 10, 20, 30, 40, 50])
print(b1[1:4])
print(b1[:3])
print(b1[2:])
b1[2:5] = np.array([25, 35, 45])
print(b1)
b1[3:6] = 60
print(b1)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]
[ 0 10 25 60 60 60]


In [183]:
b2 = np.arange(10, 100, 10).reshape(3,3)
print(b2, '\n')
print(b2[1:3, 1:3], '\n')
print(b2[:3, 1:], '\n')
print(b2[1][0:2],'\n')

b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])  #0행 1열, 1행 2열까지 박스구간 값을 변경
print(b2)

[[10 20 30]
 [40 50 60]
 [70 80 90]] 

[[50 60]
 [80 90]] 

[[20 30]
 [50 60]
 [80 90]] 

[40 50] 

[[10 25 35]
 [40 55 65]
 [70 80 90]]
