### 구조적 데이터 생성하기

#### Series를 활용한 데이터 생성

In [1]:
import pandas as pd
import numpy as np

In [9]:
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1, '\n')
print(s1.index, '\n')
print(s1.values)

0    10
1    20
2    30
3    40
4    50
dtype: int64 

RangeIndex(start=0, stop=5, step=1) 

[10 20 30 40 50]


In [11]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
print(s2)

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object


In [15]:
s3 = pd.Series([np.nan, 10, 30])
print(s3)


0     NaN
1    10.0
2    30.0
dtype: float64


In [18]:
index_date = ['2018-10-07', '2018-10-08', '2018-10-09', '20180-10-10']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date)
print(s4)

2018-10-07     200.0
2018-10-08     195.0
2018-10-09       NaN
20180-10-10    205.0
dtype: float64


In [29]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90 })
print(s5, '\n')
print(s5['영어'])

국어    100
영어     95
수학     90
dtype: int64 

95


#### 날짜 자동 생성: date_range

In [40]:
print(pd.date_range(start = '2019-01-01', end = '2019.01.07'), '\n')
print(pd.date_range(start = '2020/01/01', end = '2020/01/07'), '\n')
print(pd.date_range(start = '01-01-2019', end = '2019/01/07'), '\n')
print(pd.date_range(start = '2020-01-01', periods = 7))

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D') 

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D') 

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D') 

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')


In [49]:
print(pd.date_range(start = '2020-01-01', periods = 4, freq = '2D'), '\n')
print(pd.date_range(start = '2020-01-01', periods = 4, freq = 'W'), '\n')
print(pd.date_range(start = '2020-01-01', periods = 12, freq = '2BM'), '\n')
print(pd.date_range(start = '2020-01-01', periods = 4, freq = 'QS'), '\n')
print(pd.date_range(start = '2020-01-01', periods = 3, freq = 'AS'), '\n')

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05', '2020-01-07'], dtype='datetime64[ns]', freq='2D') 

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26'], dtype='datetime64[ns]', freq='W-SUN') 

DatetimeIndex(['2020-01-31', '2020-03-31', '2020-05-29', '2020-07-31',
               '2020-09-30', '2020-11-30', '2021-01-29', '2021-03-31',
               '2021-05-31', '2021-07-30', '2021-09-30', '2021-11-30'],
              dtype='datetime64[ns]', freq='2BM') 

DatetimeIndex(['2020-01-01', '2020-04-01', '2020-07-01', '2020-10-01'], dtype='datetime64[ns]', freq='QS-JAN') 

DatetimeIndex(['2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='AS-JAN') 



In [9]:
print(pd.date_range(start = '2020-01-01 08:00', periods = 10, freq = 'H'), '\n')
print(pd.date_range(start = '2020-01-01 08:00', periods = 10, freq = 'BH'), '\n')
print(pd.date_range(start = '2020-01-01 10:00', periods = 4, freq = '30min'), '\n')

DatetimeIndex(['2020-01-01 08:00:00', '2020-01-01 09:00:00',
               '2020-01-01 10:00:00', '2020-01-01 11:00:00',
               '2020-01-01 12:00:00', '2020-01-01 13:00:00',
               '2020-01-01 14:00:00', '2020-01-01 15:00:00',
               '2020-01-01 16:00:00', '2020-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='H') 

DatetimeIndex(['2020-01-01 09:00:00', '2020-01-01 10:00:00',
               '2020-01-01 11:00:00', '2020-01-01 12:00:00',
               '2020-01-01 13:00:00', '2020-01-01 14:00:00',
               '2020-01-01 15:00:00', '2020-01-01 16:00:00',
               '2020-01-02 09:00:00', '2020-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='BH') 

DatetimeIndex(['2020-01-01 10:00:00', '2020-01-01 10:30:00',
               '2020-01-01 11:00:00', '2020-01-01 11:30:00'],
              dtype='datetime64[ns]', freq='30T') 



In [14]:
index_date = pd.date_range(start = '2020-03-01', periods = 5, freq = 'D')
print(pd.Series([51, 62, 55, 49, 58], index = index_date))

2020-03-01    51
2020-03-02    62
2020-03-03    55
2020-03-04    49
2020-03-05    58
Freq: D, dtype: int64


#### DataFrame을 활용한 데이터 생성

In [2]:
pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
data_list = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [9]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
index_data = pd.date_range('2020-09-01', periods = 4)
columns_list = ('A', 'B', 'C')
pd.DataFrame(data, index = index_data, columns = colums_list)

A   B   C
2020-09-01   1   2   3
2020-09-02   4   5   6
2020-09-03   7   8   9
2020-09-04  10  11  12

In [28]:
table_data = {'연도': [2015, 2016, 2016, 2017, 2017],
              '지사': ['힌국', '한국', '미국', '한국', '미국'],
              '고객 수': [200, 250, 450, 300, 500]}

print(table_data)
df = pd.DataFrame(table_data, columns = ['연도', '지사', '고객 수']) 
df


{'연도': [2015, 2016, 2016, 2017, 2017], '지사': ['힌국', '한국', '미국', '한국', '미국'], '고객 수': [200, 250, 450, 300, 500]}


연도  지사  고객 수
0  2015  힌국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [31]:
print(df.index)
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=5, step=1)
Index(['연도', '지사', '고객 수'], dtype='object')
[[2015 '힌국' 200]
 [2016 '한국' 250]
 [2016 '미국' 450]
 [2017 '한국' 300]
 [2017 '미국' 500]]


### 데이터 연산

In [38]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2, '\n')
print(s2 - s1, '\n')
print(s1 * s2, '\n')
print(s2 / s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64 

0     9
1    18
2    27
3    36
4    45
dtype: int64 

0     10
1     40
2     90
3    160
4    250
dtype: int64 

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


In [42]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])
print(s3 + s4, '\n')
print(s4 - s3, '\n')
print(s3 * s4, '\n')
print(s4 / s3)

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64 

0     9.0
1    18.0
2    27.0
3    36.0
4     NaN
dtype: float64 

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64 

0    10.0
1    10.0
2    10.0
3    10.0
4     NaN
dtype: float64


In [48]:
table_data1 = {"A": [1, 2, 3, 4, 5],
              "B": [10, 20, 30, 40, 50],
              'C': [100, 200, 300, 400, 500]}
df1 = pd.DataFrame(table_data1)
df1



A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [49]:
table_data2 = {'A': [6, 7, 8],
              'B': [60, 70, 80],
              'C': [600, 700, 800]}

df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [51]:
df1 + df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [65]:
table_data3 = {'봄': [256.5, 264.3, 352, 252.4, 123.4],
             '여름': [111, 222, 333, 444, 555],
             '가을': [666, 777, 888, 999, 101],
             '겨울': [131, 50, 60, 70, 80]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3


봄   여름   가을   겨울
2012  256.5  111  666  131
2013  264.3  222  777   50
2014  352.0  333  888   60
2015  252.4  444  999   70
2016  123.4  555  101   80

In [77]:
print(df3.mean(), '\n')       ##평균
print(df3.std(), '\n')        #표준 편차
print(df3.mean(axis = 1), '\n')  # 행별 평균  axis 값이 0이면 열별 평균
print(df3.std(axis = 1))                    # 행별 표준 편차



봄     249.72
여름    333.00
가을    686.20
겨울     78.20
dtype: float64 

봄      81.675682
여름    175.506410
가을    349.885267
겨울     31.562636
dtype: float64 

2012    291.125
2013    328.325
2014    408.250
2015    441.350
2016    214.850
dtype: float64 

2012    258.079566
2013    313.144412
2014    346.537516
2015    401.905242
2016    227.458033
dtype: float64


In [81]:
df3.describe()

봄         여름          가을          겨울
count    5.000000    5.00000    5.000000    5.000000
mean   249.720000  333.00000  686.200000   78.200000
std     81.675682  175.50641  349.885267   31.562636
min    123.400000  111.00000  101.000000   50.000000
25%    252.400000  222.00000  666.000000   60.000000
50%    256.500000  333.00000  777.000000   70.000000
75%    264.300000  444.00000  888.000000   80.000000
max    352.000000  555.00000  999.000000  131.000000

### 데이터를 원하는 대로 선택하기

In [93]:
import pandas as pd
import numpy as np

KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
           '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
           '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
           '전라선 KTX': [309, 1771, 1954, 2244, 3145, 3945, 5766],
           '동해선 KTX': [np.nan, np.nan, np.nan, np.nan, 2395, 3786, 6667]}

col_list = ['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
df_KTX



경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3145   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [101]:
print(df_KTX.index, '\n')
print(df_KTX.columns, '\n')
print(df_KTX.values, '\n')
print(df_KTX.head(3), '\n')           #위에서 n행 출력  (디폴트는 5행)
print(df_KTX.tail(4))                #아래서 n행 출력   (디폴트는 5열)

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object') 

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object') 

[[39060.  7313.  3627.   309.    nan]
 [39896.  6967.  4168.  1771.    nan]
 [42005.  6873.  4088.  1954.    nan]
 [43621.  6626.  4424.  2244.    nan]
 [41702.  8675.  4606.  3145.  2395.]
 [41266. 10622.  4984.  3945.  3786.]
 [32427.  9228.  5570.  5766.  6667.]] 

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN 

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3145   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0


In [108]:
df_KTX[2:5]  #n ~n-1행 출력(행렬 아님)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3145   2395.0

In [119]:
print(df_KTX.loc['2011'], '\n')
print(df_KTX.loc['2013':'2016'], '\n\n')

print(df_KTX['경부선 KTX'], '\n')
print(df_KTX['경부선 KTX']['2012':'2014'], '\n')
print(df_KTX['경부선 KTX'][2:5])

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64 

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3145   2395.0
2016    41266    10622     4984     3945   3786.0 


2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64 

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64 

2013    42005
2014    43621
2015    41702
Name: 경부선 KTX, dtype: int64


In [129]:
print(df_KTX.loc['2016']['호남선 KTX'])
print(df_KTX.loc['2016', '호남선 KTX'])
print(df_KTX['호남선 KTX']['2016'])
print(df_KTX['호남선 KTX'][5])
print(df_KTX['호남선 KTX'].loc['2016'])

10622.0
10622
10622
10622
10622


In [132]:
df_KTX.T   #행렬을 바꾸어준다.
df_KTX[['동해선 KTX', '전라선 KTX', '경전선 KTX', '호남선 KTX', '경부선 KTX']]

동해선 KTX  전라선 KTX  경전선 KTX  호남선 KTX  경부선 KTX
2011      NaN      309     3627     7313    39060
2012      NaN     1771     4168     6967    39896
2013      NaN     1954     4088     6873    42005
2014      NaN     2244     4424     6626    43621
2015   2395.0     3145     4606     8675    41702
2016   3786.0     3945     4984    10622    41266
2017   6667.0     5766     5570     9228    32427

### 데이터 통합하기

#### 세로 방향으로 통합하기

In [144]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                   'Class2': [91, 93, 97, 99]})

df2 = pd.DataFrame({'Class1': [87, 89],
                   'Class2': [85, 90]})

df3 = pd.DataFrame({'Class1': [96, 83]})
## append로 행단에 추가할 수 있다.
df1.append(df2, ignore_index = True) #기존 인덱스 무시하고 통합한다는 뜻. 디폴트는 Flase

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

In [146]:
df2.append(df3, ignore_index = True)

Class1  Class2
0      87    85.0
1      89    90.0
2      96     NaN
3      83     NaN

#### 가로 방향으로 통합하기

In [147]:
df4 = pd.DataFrame({'Class3': [93, 91, 95, 98]})
df1.join(df4)
#join메서드로 테이블을 열단에 추가할 수 있다.

Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98

In [159]:
index_label = ['a', 'b', 'c', 'd']
df1a = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 97, 99]}, index = index_label)
df4a = pd.DataFrame({'Class3': [93, 91, 95, 98]}, index = index_label)
 ## 인덱스를 일치시켜야 values가 나옴

df1a.join(df4)

Class1  Class2  Class3
a      95      91     NaN
b      92      93     NaN
c      98      97     NaN
d     100      99     NaN

In [162]:
df5 = pd.DataFrame({'Class4': [82, 92]})

df1.join(df5)

Class1  Class2  Class4
0      95      91    82.0
1      92      93    92.0
2      98      97     NaN
3     100      99     NaN

#### 특정 열을 기준으로 통합하기

In [211]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                      '제품A': [100, 150, 200 ,130],
                      '제품B': [90, 110, 140, 170]})
df_C_D = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                      '제품C': [112, 141, 203 ,134],
                      '제품D': [90, 110, 140, 170]})

df_A_B.merge(df_C_D)

판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  140
3  4월  130  170  134  170

In [177]:
df_left = pd.DataFrame({'key': ['A', 'B', 'C'], 'left': [1, 2, 3]})
df_right = pd.DataFrame({'key': ['A', 'B', 'D'], 'left': [4, 5, 6]})

df_left.merge(df_right, how = 'left', on = 'key')

key  left_x  left_y
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [180]:
df_left.merge(df_right, how = 'right', on = 'key')

key  left_x  left_y
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [179]:
df_left.merge(df_right, how = 'outer', on = 'key')

key  left_x  left_y
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [181]:
df_left.merge(df_right, how = 'inner', on = 'key')

key  left_x  left_y
0   A       1       4
1   B       2       5

### 데이터 파일을 읽고 쓰기

#### 표 형식의 데이터 파일을 읽기

In [182]:
%%writefile C:\myPycode\data\sea_rain1.csv

연도, 동해, 남해, 서해, 전체
1996, 17.4629, 17.2288, 14.436, 15.9067
1997, 17.4116, 17.4892, 14.8248, 16.1526
1998, 17.5944, 18.011, 15.2512, 16.6044
1999, 8.1495, 18.3175, 14.8979, 16.6284
2000, 17.9288, 18.1766, 15.0504, 16.6178

Writing C:\myPycode\data\sea_rain1.csv


In [184]:
pd.read_csv('C:\myPycode\data\sea_rain1.csv')

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4892  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999   8.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [192]:
pd.read_csv('C:\myPycode\data\sea_rain1_from_notepad.csv', encoding = "cp949")

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [204]:
%%writefile C:\myPycode\data\sea_rain1.txt

연도 동해 남해 서해 전체
1996 17.4629 17.2288 14.436 15.9067
1997 17.4116 17.4892 14.8248 16.1526
1998 17.5944 18.011 15.2512 16.6044
1999 8.1495 18.3175 14.8979 16.6284
2000 17.9288 18.1766 15.0504 16.6178

Overwriting C:\myPycode\data\sea_rain1.txt


In [205]:
pd.read_csv('C:\myPycode\data\sea_rain1.txt', sep = " ")

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4892  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999   8.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [208]:
pd.read_csv('C:\myPycode\data\sea_rain1.csv', index_col = '연도')

동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4892  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999   8.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

표 형식의 데이터를 파일로 쓰기

In [219]:
df_WH = pd.DataFrame({'weight': [62, 67, 55, 74],
                      'height': [165, 177, 160, 180]},
                     index = ['ID_1', 'ID_2', 'ID_3', 'ID_4'])

df_WH.index.name = 'User'
bmi = df_WH['weight']/(df_WH['height']/100)**2
df_WH['BMI'] = 

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    23.503556
dtype: float64

In [ ]:
bmi = df_WH['weight']/(df_WH['height']/100)**2
bmi